services:
  # Cambiado a api-service para unificar el DNS con Kubernetes
  api-service:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/backend
    restart: always

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "80:80" # Tu app principal seguirá abriendo en http://localhost
    depends_on:
      - api-service # Apesta al nuevo nombre unificado
    restart: always